### ISSUE TITLE
[React 15.3.0] React.PropTypes validation will be deprecated in a future version of React; Error on mounting new components after scene init

### ISSUE THREAD

**Issue by DodekaHydra** [toxicFork/react-three-renderer#100]
Just upgraded to React 15.3. I get console.warn spam on what appears to be every React3 component.

The root cause is the `checkPropTypes` method of `THREEElementDescriptor.js`

Here's the full error:
`Warning: You are manually calling a React.PropTypes validation function for the `fog` prop on `scene`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

Update:

Mounting a TorusKnot Mesh component to a preexisting scene raises the following exception:

`InternalComponent.js:619 Uncaught TypeError: Cannot set property 'parentMarkup' of null`

**Comment by DodekaHydra** [comment]
Here's the stack trace from that error:
![Stack Trace](https://cloud.githubusercontent.com/assets/4563407/17683814/1e9b0054-630b-11e6-9111-5c1f543d9b50.png)

**Comment by Carnewal** [comment]
See #94, it's fixed in staging/2.3

**Comment by toxicFork** [comment]
Should be fixed in the new `2.3.0` release :)
