### ISSUE TITLE
Use BufferGeometry as a resource?

### ISSUE THREAD

**Issue by oortlieb** [toxicFork/react-three-renderer#105]
I'm putting an application together that requires a number of geometry resources. Some of the imported geometries are fairly complex (500k vertices after merging). Three.js hangs when trying to convert these large BufferGeometry objects into Geometries, which I can place into resources.

Is there a way to add BufferGeometries to resources? Or is there an alternative to using Three.js's Geometry.fromBufferGeometry method?

**Comment by toxicFork** [comment]
Hi @oortlieb , I will need to implement that, for now as a workaround you can create the mesh manually and add into your groups or scenes e.g.
```jsx
<scene ref={mySceneRef} > 
    ...
```

and on `componentDidMount`:
```jsx
myScene.add(new THREE.Mesh(myBufferGeometry, myMaterial));
```

**Comment by oortlieb** [comment]
@toxicFork Thanks for the info. Any estimate as to the level of effort and timeline for getting BufferGeometry support added? If it's not on your short-term road map, I might give it a shot myself.

**Comment by toxicFork** [comment]
I have done a simple implementation in 306e777a9c50cc77dd9ad9e4e8cab5c62e2db292 which will allow you to create a buffer geometry and set the 4 attributes, when I have more time ( should be able to get back to work on more r3r stuff soon :D ) I'll be able to fix some other bugs and cut a new release with it :)

Unfortunately no timeline since I can only work on this after work or in weekends when I am not occupied with other things

**Comment by oortlieb** [comment]
Looks like it works -- thanks a ton!

**Comment by martunta** [comment]
is this now part of the release? There is nothing in the docs. Or I should get this specific commit? I have exactly the same problem as @oortlieb

**Comment by toxicFork** [comment]
Ah I haven't merged it to master yet but it should be in for the next release

**Comment by martunta** [comment]
cool. can't wait. When is next release scheduled?

**Comment by toxicFork** [comment]
Ah sorry I thought I had replied earlier... I was aiming for a release today but unfortunately I did not have much time. Current ETA for a release is sometime this week ( latest Thursday when I should have more time in the evening :) )

**Comment by toxicFork** [comment]
I should be able to do a release tomorrow evening :)
