### ISSUE TITLE
Update for three@0.80.1?

### ISSUE THREAD

**Issue by kevinhikaruevans** [toxicFork/react-three-renderer#106]
I followed the instructions listed in the README, and three is now at 0.80.1, whereas this package requires < 0.80.0.

`npm WARN react-three-renderer@2.3.1 requires a peer of three@>=0.78.0 < 0.80.0 but none was installed.`

**Comment by toxicFork** [comment]
I should fix the instructions in readme or fix compatibility, thanks for pointing it out!
