### ISSUE TITLE
This resource was not in this map?

### ISSUE THREAD

**Issue by DelvarWorld** [toxicFork/react-three-renderer#11]
My application is crashing with the error:

    This resource was not in this map?

On [this line](https://github.com/toxicFork/react-three-renderer/blob/227a8683a4b346d12f41459d1027823745d79d1c/src/descriptors/Resource/ResourceDescriptorBase.js#L162).

I don't have a standalone test case, but I'm switching between two `<React3>` top level components and both top level components have the same `<MyObjects />` component as a child, which holds its own resources. Strangely, I can only reproduce the bug if I scale one of my objects down. I don't think this is directly causing the issue but maybe exposing something that is.

**Comment by toxicFork** [comment]
I'll be able to take a look in a couple days!

**Comment by DelvarWorld** [comment]
More info:

This seems to be happening when a child of a scene has a `<resource>` in it. As in my child has:

`<group><resource>...</resources><meshh /></group>`

My use case is this child is in the scene, then I re-render the child with new props, then I replace the top level `<React3>` component with a new `<React3>` component, and I get the error. However, if I move the `<resource>` group in the child to the parent component (containing the first `<React3>`) then the error goes away.

**Comment by toxicFork** [comment]
How do you replace the component, what do you mean by a "new" react3 component? With react, if you want to replace, you may need to change a "key" property

**Comment by toxicFork** [comment]
Having troubles reproducing it... Please let me know when you run into it next @DelvarWorld

**Comment by toxicFork** [comment]
Closing issue until it can be reproduced, please feel free to reopen
