### ISSUE TITLE
Simple point rendering example

### ISSUE THREAD

**Issue by gijs** [toxicFork/react-three-renderer#111]
Hi,

Thx for this great library!

For a 3D beginner it's still quite daunting though.. 

My question: Is there some simple code somewhere which demonstrates how react-three-renderer can be made to draw a couple of white points in a cartesian coordinate system?

Can anyone point me in a direction to achieve this? (ie. basic setup, components to use etc)

The react-three-renderer examples are quite involved and specific, and I couldn't use them as a startingpoint as such.

thx!

**Comment by Colmea** [comment]
Since it's not an issue, you should come in the [gitter react-three-renderer chatroom ](https://gitter.im/toxicFork/react-three-renderer) and ask your question there ;)

**Comment by gijs** [comment]
Will do! Thanks!
