### ISSUE TITLE
Can I access the renderer.domElement?

### ISSUE THREAD

**Issue by Fabiantjoeaon** [toxicFork/react-three-renderer#115]
Is this possible? I'm trying to add dom events ( using https://github.com/jeromeetienne/threex.domevents ).

I don't believe adding a ref to my React3 and then access the canvas ref is working..

If you have any other solution, or maybe manually using a raycaster, it would be appreciated (for which I also need the renderer.domElement)

TIA

**Comment by toxicFork** [comment]
I think the canvasRef prop (pass a function, it's like a ref function)
should help you do that but if that doesn't work it could be a bug or
potential improvement :)

https://github.com/toxicFork/react-three-renderer/wiki/Entry-Point#canvasref

**Comment by Fabiantjoeaon** [comment]
Thanks for the quick response! 
Passing a function to the canvasRef property crashes my scene..

This is my React3 object
`<React3
	canvasRef={(ref) => this._renderer = ref}
	mainCamera='camera'
	width={this.width}
	height={this.height}
	antialias
	alpha={true}
	clearAlpha={0}
	onAnimate={this._onAnimate}
>`

And my console tells me.. well..

<img width="431" alt="schermafbeelding 2016-10-09 om 15 54 14" src="https://cloud.githubusercontent.com/assets/4189340/19220915/b39b3d9c-8e38-11e6-9ccf-60116e962eb2.png">

**Comment by toxicFork** [comment]
It looks like I forgot to implement the update function for the property

I'll take a look when I am free next ( monday or tuesday evening GMT )

For refs I'd recomment not to use arrow lambdas because they will be
different every time, try something like this:

```jsx
canvasRef={this.canvasRef}
```

Where canvasRef is a function defined for your class. That should prevent
it from being called every render. I am guessing there may be another bug
for your case but I'll resolve the update handling first and see how far
that'll take us :)

**Comment by Fabiantjoeaon** [comment]
Aha I see, I'll change that.

As React is an UI library, treating React3 components as 'DOM components' (simulating DOM events like mouseover and click on meshes) can be extremely powerful to create awesome dynamic 3D UI's (when mixed with the real DOM of course), so I hope that we can make this work, it's the main reason I use your project.

Please let me know & thanks for your support :).

**Comment by toxicFork** [comment]
I have something very experimental to achieve that partially: modules:

Example mouse input module:
https://github.com/toxicFork/react-three-renderer-example/blob/master/src/examples/inputs/MouseInput.js

Example usage of said module:
https://github.com/toxicFork/react-three-renderer-example/blob/master/src/examples/DraggableCubes/index.js
search
for `mouseInput` to see how I used it

I will extract mouse input to a separate module with usage instructions (
high on my todo list) and document modules to allow others to make them (
slightly lower in todo list but still there )

**Comment by Fabiantjoeaon** [comment]
Looks very promising. I've got a lot of questions but I guess I'll just wait for your usage instructions :). Looks like a more logical, if not, easier way to tackle my problem.

Until your mouseInput module is ready for use I'll stick with the threex.domevents library.

**Comment by Colmea** [comment]
Note that I'm using mouseInput module in production right now, and it works pretty well !
I think it's the react way to do it, since you can do this with mouseInput:
`<myMesh onClick={this.onClickMesh} />`

like a simple html element :) .

**Comment by Fabiantjoeaon** [comment]
Awesome. Is this in version 2.3.2? I can't seem to find it @Colmea

**Comment by toxicFork** [comment]
I think @Colmea may have created a copy of the module in their project to use.

Regarding `canvasRef` bugs I'm adding some changes that should help fix the problems today :)
