### ISSUE TITLE
input events

### ISSUE THREAD

**Issue by wishfoundry** [toxicFork/react-three-renderer#12]
Hi,

Do you have any plans to integrate inputs(e.g. mouse collision events) with this, or any examples if you already can?

Also, have you considered opening a room on https://gitter.im/ or similar, where more conversational questions might go instead of cluttering up to the issues board?

**Comment by wishfoundry** [comment]
found it:
https://github.com/toxicFork/react-three-renderer-example/blob/master/src/examples/DraggableCubes/

**Comment by toxicFork** [comment]
Hi, sure I will open a room on gitter.im :) And yes that's a good example for input!

**Comment by tkiethanom** [comment]
Has anyone gotten mouse events to work recently? I copied the MouseInput.js and added the `<module
          ref={elem => (this.mouseInput = elem)}
          descriptor={MouseInput}
        />`. When I set on my `<mesh onMouseEnter={console.log('test')}>` it never fires. I updated the way refs work in the latest React, I'm guessing that's the problem.
