### ISSUE TITLE
Compatibility with three@>=0.80.0

### ISSUE THREAD

**Issue by foorjdev** [toxicFork/react-three-renderer#124]
I've managed to update r3r to be compatible with the ES6 versions of three.js (specifically 0.82.1, though anything >=0.80.0 should work fine apart from failing tests that check the console output for the exact version, e.g. "THREE.WebGLRenderer 82"). 

You can take a look at my fork [here](https://github.com/foorjdev/react-three-renderer). 

The vast majority of modified files only had `import THREE from 'three';` changed to `import * as THREE from 'three';` since there's no default export now. I also fixed a PropTypes issue having to do with `TubeGeometry.FrenetFrames` moving to `Curve.computeFrenetFrames`.

Unfortunately I ran into a bit of a stumbling block on two of the tests for `TextureLoader`. The tests are written to replace `THREE.ImageLoader` with a stub (for example, `imageLoaderLoadStub = sinon.stub(THREE, 'ImageLoader', ImageLoaderMock);` in tests/src/descriptors/Texture.jsx), but since the `THREE` namespace is no longer used internally, the replacement has no effect on the function called internally by `TextureLoader`. The result is that the `ImageLoaderMock` test function is never called, leading to an error being thrown by `expect(imageLoaderInstances.length).to.equal(1);`. 

If anyone can offer some guidance on how I should proceed, I'd really appreciate it. I have very little experience with test frameworks like mocha, so it's difficult for me to discern the correct approach at times.

**Comment by toxicFork** [comment]
Cool, good work! :D I really appreciate it!

Start a pull request, and I can do PRs to your fork to show how to approach fixing the tests if you like.

I should have some time this weekend :)
