### ISSUE TITLE
Progressively use react-three-renderer in existing project

### ISSUE THREAD

**Issue by bjnortier** [toxicFork/react-three-renderer#130]
I would like to use react-three-renderer in an existing project, but I am reluctant to do convert the whole project (~11k LOC, a lot of it three.js). 

Is there a way to start from the bottom up? I.e. start with the THREE.Mesh objects and attach them to existing vanilla three.js scenes, and then move up the hierarchy and finally use top-level <React3><scene>...</scane></React3> components?

Thanks

**Comment by toxicFork** [comment]
Hmm... If it was pure React I'd say you can convert some inner DOM elements, bottom up, to React components... I think with R3R you can try to go the other way, top down...

For bottom-up we may need to implement rendering things into already existing scenes... and I don't think that was considered as a use case.

For example, to begin with:

```
componentDidMount(){
    this.refs.myScene.add(/* everything in your scene goes here */);
}

render() {
    <React3>
        <scene ref="myScene"/>
    </React>
}
```

But, also need to think, is it going to be worth it to convert things to r3r?

**Comment by bjnortier** [comment]
If you can't render r3r components into existing scenes then I might have to go top down as you suggested - could work as well.

The rest of the app is being converted to React+Redux I want some conformity and re-use. Right now I have a way of shimming things in but it's not elegant.

Thanks for the help!

**Comment by toxicFork** [comment]
I'm still going to keep this in my "would be good to have" list, because if the project stays popular it may be a very useful feature.
