### ISSUE TITLE
meshLambertMaterial missing options?

### ISSUE THREAD

**Issue by kevzettler** [toxicFork/react-three-renderer#132]
specifically looking for `vertexColors`

https://threejs.org/docs/#Reference/Materials/MeshLambertMaterial

> vertexColors — Define how the vertices gets colored. Default is THREE.NoColors.

**Comment by toxicFork** [comment]
Looks like `pointsMaterial`, `lineDashedMaterial` and `lineBasicMaterial` has that prop, but I'll be bringing it up to Material
