### ISSUE TITLE
happen some ui error when making a removing operation

### ISSUE THREAD

**Issue by xiaoxuez** [toxicFork/react-three-renderer#135]
Apologies in advance if this is a basic question -- I'm in the process of learning React and this library.     =.=

specific situation :  
   1.  I need dynamic operation to add or remove mesh just like a simple editor.
   2. My initial data stem from object imported.  I keep it as a array in state.
  3.  when adding or removing , I change the array (splice by object) directly.  and setState.

unexpected ：
  whichever i remove,   this comes out the last one  to disappear。

I think I ignore something about re-rendering, maybe. Can you give me some advise?

**Comment by toxicFork** [comment]
Can you please paste the code, it could help resolve the issue

**Comment by xiaoxuez** [comment]
=.=     thanks simida~

just a simple demo extends from your example of DraggableCubes.  So I just paste some differ code.
    + and - codes
 ` onIncreaseClick() {
    let p_x = Math.random() * 150 - 50;
    let p_y = Math.random() * 150 + 60;
    let p_z = Math.random() * 120 - 60;
    this.models.push({position: new THREE.Vector3(p_x, p_y, p_z)});
    this.setState({
      models: this.models,
    })
  }

  onDecreaseClick() {
    this.selecteModel.parent.remove(this.selecteModel);
    // this.models.splice(this.selected, 1);
    // this.setState({
    //   models: this.models,
    // })
    this.setState({})  // to re-render
  }`

  when click someone,

`  setChoiceItem(models, choice) {
    this.selected = choice;  //index of this.models
    this.selecteModel = models;    // refs of it
  }`

  in render 
 ` ...
   <scene>
    <TouchableModels models={this.state.models}
            onCubesMounted={this._onCubesMounted.bind(this)}
            mouseInput={mouseInput}
            camera={camera}
            setChoiceItem={this.setChoiceItem.bind(this)}/>
  </scene>`


when i click someone ,  will callback setChoiceItem.  then i click remove --> onDecreaseClick. in method of onDecreaseClick, if use the code annotated, whichever i remove, this comes out the last one to disappear.  then i try to use   `this.selecteModel.parent.remove(this.selecteModel);` . but there will be wrong when i use draggable mesh because of i cant control the doms,  maybe

**Comment by xiaoxuez** [comment]
I have dealed with it today. The problem is about re-rendering specific cubes. thanks at all.
