### ISSUE TITLE
Missing props for `pointsMaterial`

### ISSUE THREAD

**Issue by khiner** [toxicFork/react-three-renderer#138]
When trying to create a textured point, I get the following errors:
```
Warning: Foreign prop map found in pointsMaterial
Warning: Foreign prop blending found in pointsMaterial.
Warning: Foreign prop depthTest found in pointsMaterial.
```

preventing me from using a texture on a point.

My usage:
```
  this.circleSprite = new THREE.TextureLoader().load(require('../textures/sprites/circle.png'));
  ...

  render() {
    return (<points>
      ...
      <pointsMaterial
        color={0x888888}
        size={50}
        map={this.circleSprite}
        blending={THREE.AdditiveBlending}
        depthTest={false}
        transparent={true}
      />
```

It looks like [PointsMaterialDescriptor](https://github.com/toxicFork/react-three-renderer/blob/master/src/lib/descriptors/Material/PointsMaterialDescriptor.js) is indeed missing all of these possible attributes, although Three does have them as [options](https://github.com/mrdoob/three.js/blob/dev/src/materials/PointsMaterial.js)

**Comment by toxicFork** [comment]
Thanks for the report, I will be fixing these.

**Comment by khiner** [comment]
Thanks for getting on this so quickly! I tried to take it on myself but ran into weird issues locally after doing an `npm link` to my copy, where it was saying things along the lines of `Invalid prop: ...Material expected blah to be of type Vertex but found type Vertex` and others like that.  Like its comparison between object types would fail if it found my local reference to `THREE.Blah` when it expected a different `THREE.blah`.

Anyway, thanks again :)

**Comment by toxicFork** [comment]
Hmm that happens if there are different versions of THREE present in both
projects, it can happen with links if there are separate installations, I
may need to add that into ghee notes for using link

**Comment by khiner** [comment]
Ah, that's exactly what I assumed was happening, couldn't think of another way the class comparison would fail.  Good tip on npm install-ing the directory path.
