### ISSUE TITLE
Doesn't build with latest babel

### ISSUE THREAD

**Issue by DelvarWorld** [toxicFork/react-three-renderer#15]
./react-three-renderer (three) $ gulp babel
    [14:18:05] Requiring external module babel-core/register
    ./react-three-renderer/node_modules/babel-core/lib/transformation/file/logger.js:41
        throw new Constructor(this._buildMessage(msg));
        ^

    ReferenceError: [BABEL] ./react-three-renderer/gulpfile.babel.js: Unknown option: base.stage

Looks related: https://github.com/babel/babelify/issues/129

**Comment by toxicFork** [comment]
https://github.com/toxicFork/react-three-renderer/pull/16 Resolves it
