### ISSUE TITLE
Three v84

### ISSUE THREAD

**Issue by mbodge** [toxicFork/react-three-renderer#151]
I'm curious if there's a plan to upgrade to v84 anytime soon. I see v82 is still a dependency and I'm trying to build a project using things only available in 83+. I've tried to use the updated version of Three from npm with react3 and it throws errors. Specifically i'm looking to use RectAreaLight.

Thanks!

**Comment by toxicFork** [comment]
On it! :D Hopefully it should "just work" but I'll confirm.

**Comment by toxicFork** [comment]
It broke some things again 😭 I'll find workarounds. Looks like it's mostly about testing at the moment so nothing too bad... yet :P

**Comment by ashl1** [comment]
I think this issue can be closed as current dependency is ~0.86

**Comment by toxicFork** [comment]
Cheers :D
