### ISSUE TITLE
requestAnimationFrame error when testing

### ISSUE THREAD

**Issue by matthova** [toxicFork/react-three-renderer#163]
When used with create-react-app, requestAnimationFrame throws an error.

*Note* basic coverage test "it('renders without crashing')" will fail as of react-three-renderer v3.1.0.
Proposed solution is to wrap 'react-three-renderer/lib/React3Instance.js' line 262 in the following code:
```
if (typeof requestAnimationFrame === 'function') {
  this._renderRequest = requestAnimationFrame(this._render); // Line 262
}
```

Note, this might not be the right solution, but it did make the errors go away. @toxicFork would love to get your take on the error.

Here are the steps to recreate the error:
```
git clone https://github.com/matthova/React-threeJS-UI-boilerplate.git
cd React-threeJS-UI-boilerplate/
npm install
npm test
```

**Comment by toxicFork** [comment]
Thanks for the report :) I'm guessing the test fails because it doesn't use a browser with a 3d context... but it would make sense to suppress this anyway, or at least use a shim for RAF.

**Comment by matthova** [comment]
I can make a pull request with 
```
if (typeof requestAnimationFrame === 'function') {
  this._renderRequest = requestAnimationFrame(this._render); // Line 262
}
```

Before I do, is this an acceptable way to go about it?

**Comment by toxicFork** [comment]
Linking #164 to it
