### ISSUE TITLE
shouldUpdate for Animation frame

### ISSUE THREAD

**Issue by pedro-iago** [toxicFork/react-three-renderer#17]
So I am looking at Chrome Devtools, in the Timeline tab for my [app](https://github.com/pedro-iago/rack-physics/tree/experimental), and I am noticing some react3 re-renders triggered by Animation Frame that, I believe, represent wasted executions of the React virtual dom diffing, resulting in no actual changes to the threejs objects: 

![image](https://cloud.githubusercontent.com/assets/7795187/12074354/f8616148-b12c-11e5-952e-131ea32c7f74.png)
(The first with longer duration I am sure is doing the job, updating them, but the following three I feel like are just wasting time... A similar pattern repeats.)

So I would like to know if there could be an use for [canceling an animation frame](https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame) conditionally, within the onAnimate function, maybe by exposing the requestAnimationFrame return value to it, or even by exposing the requestAnimationFrame call itself. 

In a way that could effectively work as an shouldComponentUpdate parallel for three.js objects, if I am not missing something... What do you think?

**Comment by toxicFork** [comment]
That is a good idea :) I'm thinking of adding a separate prop perhaps,
maybe "should render this frame"? Or will implement and document manual
rendering options

**Comment by pedro-iago** [comment]
Nice!! I am trying to wrap my head about React reconciliation with the DOM... Maybe shouldn't we only request an animation after any reconciliation happened? Something like componentDidUpdate... but global...

**Comment by toxicFork** [comment]
Hi again, I did some more perf tests and ideally it shouldn't take any time at all (around 0.1ms for me) to actually render every frame, of course that's as long as a lot of react components aren't being modified. Would it be possible for you to host an example case somewhere? In the worst case I could pull your project and have a play and see where we can improve the perf :) 

I am also considering returning the RAF or something else for canceling an update, or enabling manual rendering easily.

**Comment by pedro-iago** [comment]
Awesome, it would be great to have some advises! Indeed for my case I can end up with many components at the same time... However, I can expect most of them to be usually static, and use shouldComponentUpdate to skip those. You ~~can~~ could check my project at http://pedro-iago.github.io/rack-physics/index.html, or by running the experimental branch on my [repo](https://github.com/pedro-iago/rack-physics/tree/experimental). Thanks! 

PS: I haven't figured out how to "webpack" workers on gh-pages, but at least on localhost works fine...

**Comment by pedro-iago** [comment]
If I understood right, React3Instance.render already updates only what React has changed? If so, I think my problem was really on the timing of my update in regards to the animation frame... I am thinking the ideal scenario would have one update by animation frame, and maybe because I wait for a Message Event from web workers I can't really do that, if React3Instance calls requestAnimationFrame...

On a side note, have you considered updating the three js instances on web-workers as well? It seems to me that this could be related with React3Instance.render somehow... Maybe if we send the diffs via message, we could reproduce the update on each worker, allowing them to use raycast for instance!

**Comment by toxicFork** [comment]
You could put things received from web workers into a queue and process the display related stuff in animation frame.

I know some people tried using react three renderer and/or react within web workers, may be interesting!

**Comment by toxicFork** [comment]
I haven't really considered having the internal representation within web workers but that sounds quite interesting too actually :)

**Comment by abudaan** [comment]
Something similar to 'enableRapidRender' in Izzimach's react-three library would be very welcome indeed!

**Comment by toxicFork** [comment]
Hi @abudaan @pedro-iago sorry for the late update, I have implemented the functionality and some testing around these, will do some more manual tests before I can cut a release with this :)

Current implementation suggestion:

```jsx

    <React3
      width={800}
      height={600}

      forceManualRender // bool, if true, does not automatically re-render every frame
      onManualRenderTriggerCreated={manualRenderTriggerCallback} // see below
    />

let renderTrigger;

function manualRenderTriggerCallback(trigger) {
  renderTrigger = trigger;

  renderTrigger(true); // renders immediately
  renderTrigger(true); // renders again immediately

  renderTrigger(); // renders on next requestAnimationFrame ONLY
  renderTrigger(); // no effect, can trigger only one render for "next animation frame"
}

somethingHappened() {
  // set state
  // trigger render for next frame ONLY
  renderTrigger();
}
```

Any thoughts?

**Comment by abudaan** [comment]
Thanks, that looks fine to me!

Meanwhile I made a hack to achieve somewhat the same result. Here is a [live example](http://data.tweedegolf.nl/minecraft/react-three-renderer2/). When auto render is set to 'off' I get 60 fps but and over 30% CPU load. If I set it to 'on' I get only 30 fps but less than 20% CPU load. Any thoughts on this? You can see the code [here](https://github.com/tweedegolf/minecraft-character-configurator/blob/master/react-three-renderer2/js/components/three/scene.react.js)

**Comment by toxicFork** [comment]
I think most of the CPU work is going to be wasted on recreating the geometries every time they change... Instead of modifying width/height/depth for boxes, try to set the mesh scale property instead. Updating geometries are quite expensive as they need to remount. I should add some notes for performance considerations, as it is not easily visible at the moment.

**Comment by abudaan** [comment]
Good point! I will try that.

But how do you explain the difference in CPU use between continuous rendering (on rAF) and rendering only after something has changed? Both use the same inefficient way of setting width/height/depth of boxes.

Could it be that the interval between the change events fired by the sliders is smaller than the interval between 2 successive animation frames, thus causing more calls to Three.js' render method?

**Comment by toxicFork** [comment]
Yes I think that is what is probably happening, but still, continuous rendering should not be slow, it may just eat some more battery and do "unnecessary work". Unless you have tons of objects, rendering should still be faster than other activities.

**Comment by toxicFork** [comment]
In v0.1.0, see https://github.com/toxicFork/react-three-renderer/wiki/react3#forcemanualrender and https://github.com/toxicFork/react-three-renderer/wiki/react3#onmanualrendertriggercreated
