### ISSUE TITLE
House wireframe and fill

### ISSUE THREAD

**Issue by c0debreaker** [toxicFork/react-three-renderer#173]
Hi,

This post isn't really an issue. I don't know where I can ask this question. I found three.js today as well as your react-three-renderer project. It's awesome! I started reading threejs docs but I haven't tried coding an example yet.

I would like to create a wireframe of my house but I also want to be able to put a fill color on some squares like garage door. Where should I start? What do I use to be able to create a wireframe?

Thanks,

c0debreaker

**Comment by toxicFork** [comment]
Hi!

First of all, thank you for your interest!

I would recommend using threejs by itself first, and then trying to translate it over to `react-three-renderer`, that is how I have seen others do it. But if you are feeling adventurous please go ahead and let us know how it goes :D If you have any issues write them here and I or others would love to help out!

You can start by expanding on the "simple example" in the readme. Currently this is still a bit difficult to get set up as there is a bit of magic involved but once smaller examples can be made it will hopefully be a bit nicer...

If you mean to use wireframe materials, this can be done through the `wireframe` property of the material. For example:
```
          <meshBasicMaterial
            color={0x00ff00}
            wireframe // like this :)
          />
```

To have different colors, you can change the `color` property above. For example to make a red door you can use `0xff0000` as a number, or `"#FF0000"` as a string.

If you'd like to create a house shape, you can use the `position` property of the `mesh` objects, for example:

```
        <mesh
          position={new THREE.Vector3(0,0,0)}
        >
          <boxGeometry
            width={1}
            height={1}
            depth={1}
          />
          <meshBasicMaterial
            color={0xffffff} // white
            wireframe
          />
        </mesh>
        <mesh
          position={new THREE.Vector3(1,0,0)}
        >
          <boxGeometry
            width={1}
            height={1}
            depth={1}
          />
          <meshBasicMaterial
            color={0xff0000} // red
            wireframe
          />
        </mesh>
```

This places two cubes next to each other in the world. You can also use `scale` property to stretch them (for example `scale={new THREE.Vector3(2, 1, 1)}` to make a mesh twice as wide), or place more meshes by copying and pasting the components and changing their position properties.

Have fun!

**Comment by toxicFork** [comment]
I forgot to note, if you want it to be filled you can either not use the `wireframe` property so it will be only a solid color, or have two cubes, one wireframe of the wire color you would like, and the other one not wireframe, with the fill color, but scaled a bit smaller (e.g. `(0.99, 0.99, 0.99)` (play with the value to make it work properly) in the same position.

**Comment by c0debreaker** [comment]
Awesome sir! I'll try it out soon! :)
