### ISSUE TITLE
Many doc links are broken

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer#175]
E.g. see https://github.com/toxicFork/react-three-renderer/wiki/Materials and click on the links that go to threejs docs.

Hints on how to fix:
- write a message here to say if you'd like to give it a try
- clone the repo
- search for `threejs.org/docs` in the `docs` directory
    - E.g. https://github.com/toxicFork/react-three-renderer/blob/master/docs/src/internalComponents/meshBasicMaterial.js#L5
- fix one or two of them by changing the links to correct URLs (or all if you are patient)
    - e.g. `https://threejs.org/docs/#api/materials/MeshBasicMaterial`
- run `gulp doc` to verify ( optional, can be done by @toxicFork too )
- create a PR!
- receive love and creds

**Comment by ashl1** [comment]
Should we close this issue due to merged PR?

**Comment by toxicFork** [comment]
Aww yiss! Thanks @AndrewRayCode and good shout, @ashl1 :)
