### ISSUE TITLE
Bug in GeometryDescriptorBase.js

### ISSUE THREAD

**Issue by alexhisen** [toxicFork/react-three-renderer#180]
line 48:
PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.arrayOf(THREE.Vector2))),
should instead be:
PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.arrayOf(propTypeInstanceOf(THREE.Vector2)))),

Currently it's causing Vector2() to be called as a function which results in a "cannot set property 'x' of undefined" error

**Comment by toxicFork** [comment]
Thank you for the report :)
