### ISSUE TITLE
Compatibility with three.js r85

### ISSUE THREAD

**Issue by alexanderfrey** [toxicFork/react-three-renderer#181]
Hi,

thanks for the great work. I'm trying to get react three renderer to work with the latest version of three.js r85 but encouter issues. The thing is, I'm not sure if those issues are due to compatibility with the latest library or if my code is broken.

My question is: Can you confirm the react three renderer works with r85 ? If not, do you plan an update any time soon ?

Thanks so much,
Alexander

**Comment by thierryc** [comment]
#187

**Comment by toxicFork** [comment]
This should be fixed with https://github.com/toxicFork/react-three-renderer/releases/tag/v3.2.0 , please give it a go and reopen if it has not been resolved
