### ISSUE TITLE
Can't resolve 'react/lib/ReactComponent'

### ISSUE THREAD

**Issue by IcanDivideBy0** [toxicFork/react-three-renderer#184]
Hi,
Seems the `react/lib/ReactComponent` doesn't exists anymore. So i got this error thrown

```
./~/react-three-renderer/lib/React3Renderer.js
Module not found: Can't resolve 'react/lib/ReactComponent' in '.../node_modules/react-three-renderer/lib'
```

Is there any particular reason to import react's internals ? `React.component` is basically the same ?

```
$ yarn list react react-three-renderer
yarn list v0.24.5
├─ react-three-renderer@3.1.0
└─ react@15.6.1
```
Everything worked fine w/ `react@15.5.4`

**Comment by kenta88** [comment]
I fixed this running npm install into node_modules/react-three-renderer

**Comment by bcongdon** [comment]
@kenta88's solution seems to work.

However, this has the annoying side effect of `react-three-renderer`'s pre-commit hooks getting attached to your toplevel project 😕

**Comment by toxicFork** [comment]
This should be fixed with the 3.2.0 release which will support `react@~15.6.1`

**Comment by toxicFork** [comment]
> Is there any particular reason to import react's internals ? React.component is basically the same ?

It was "the way to make your own renderer", at least until I finish the "react-three-renderer-fiber" : https://github.com/toxicfork/react-three-renderer-fiber ( no estimated time of arrival ™️ )

**Comment by toxicFork** [comment]
Please reopen if it still persists

**Comment by tmulroy** [comment]
Any chance someone can explain why cd into node_modules/react-three-renderer and running npm install fixes this?

**Comment by toxicFork** [comment]
It's because of package dependencies being strange in npm. It may cause
other problems with react, but once the latest version support gets merged
in it will be OK. The only problem is time :p
