### ISSUE TITLE
Convert Current Frame / Canvas to Image

### ISSUE THREAD

**Issue by Robinnnnn** [toxicFork/react-three-renderer#199]
I have a React3 scene that maps a panorama onto a `sphereGeometry`.

I would like a user to be able to pan to their intended view and save a thumbnail, like so:

![screen shot 2017-10-10 at 6 22 24 pm](https://user-images.githubusercontent.com/12162433/31413654-5e04d5c0-ade8-11e7-9159-ae6977069f3d.png)

I have used [`canvas.toDataURL`](https://stackoverflow.com/a/36297034/5377437) for converting the canvas view into an appropriate format for uploading to S3. Unfortunately, this simply ends up in a black image.

This [StackOverflow post](https://stackoverflow.com/questions/26193702/three-js-how-can-i-make-a-2d-snapshot-of-a-scene-as-a-jpg-image) suggests that the WebGLRenderer must be initialized using the `{preserveDrawingBuffer: true}` setting. However, I am unable to apply this setting in the context of using the `react-three-renderer` library.

The `react-three` library apparently provides the ability to pass [custom renderer props](https://github.com/Izzimach/react-three/pull/99) specifically for this purpose, but again, I'm not sure how this can be applicable to my app. Here's the basic layout of my scene:

```
<React3>
  <scene>
    <perspectiveCamera/>
    <object3D>
      {
        panoMeshes.map((face, i) => (
          <mesh
            key={i}
            position={face.position}
            rotation={face.rotation}
          >
            <sphereGeometry />
            <meshBasicMaterial>
              <texture
                key={i}
                onLoad={this.handleOnLoad}
                url={this.applyPanoFace(i)} // Pano images are loaded in as texture
              />
            </meshBasicMaterial>
          </mesh>
        ))
      }
    </object3D>
  </scene>
</React3>
```

Any help as to how I can pass `{preserveDrawingBuffer: true}` to the renderer would be much appreciated. Better yet, is there a better way to take a screenshot of the canvas view?

**Comment by toxicFork** [comment]
Ah I see, yes that feature is missing and needs to be implemented. I'll bundle it up with a few other fixes and try to release it... I am unfortunately not sure of taking screenshots in other ways as I had not tried it, but once the next version is ready it should resolve this case :)

**Comment by Robinnnnn** [comment]
Wow... `preserveDrawingBuffer` [already exists as an attribute](https://github.com/toxicFork/react-three-renderer/wiki/Entry-Point#preservedrawingbuffer) for the React3 component. Just flagging this as true got me what I wanted :)

Thanks so much!

**Comment by toxicFork** [comment]
Huh... The time machine works!
