### ISSUE TITLE
Is there a way to render a JSON model exported from blender in a component?

### ISSUE THREAD

**Issue by justinmolinaa** [toxicFork/react-three-renderer#232]
In three.js the functionality looked something like 

var loader = new THREE.JSONLoader();
loader.load('path to JSON file', addModel);

Is there a way to replicate this inside of a component?  When I tried originally i received an error : 

VM895:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.onLoad (three.module.js:37169)
    at XMLHttpRequest.<anonymous> (three.module.js:31774)

Any help would be greatly appreciated, Thank you

**Comment by xzessmedia** [comment]
obviously this is an issue board and not a forum.
the count of open issues gives impressions about the health of a repository
you should use this function to submit bugs in first line only.
