### ISSUE TITLE
texture offsets?

### ISSUE THREAD

**Issue by xseignard** [toxicFork/react-three-renderer#25]
Hello,

Thanks for this lib! It is pleasant to use it so far.

I would like to recreate this technique : [texture animation](https://github.com/stemkoski/stemkoski.github.com/blob/master/Three.js/Texture-Animation.html) with your lib. But I think we cannot manipulte the [texture offset](http://threejs.org/docs/#Reference/Textures/Texture.offset) from your lib, am I right? Or do I miss the point?

Best regards,

Xavier

**Comment by toxicFork** [comment]
That's certainly doable :)

I will add support for the offset property to textures!

**Comment by toxicFork** [comment]
@xseignard Install `react-three-renderer@0.0.18-alpha` :) https://github.com/toxicFork/react-three-renderer/wiki/texture#offset is now in :)

**Comment by xseignard** [comment]
Woah! That was quick !

Thanks for the support! I try it ASAP!

Best regards

**Comment by toxicFork** [comment]
No problems, please let me know if it doesn't work or if you have any issues :smile:

**Comment by xseignard** [comment]
Hello,
So I tried to play around, but I'm facing some issue about perf.
I'm not sure by what it is caused.

Here is the demo: http://xseignard.github.io/fi-material/

Maybe I'm doing something wrong, but I cannot see it
https://github.com/xseignard/fi-material/blob/master/src/components/App/index.jsx
https://github.com/xseignard/fi-material/blob/master/src/components/Target/index.jsx

**Comment by xseignard** [comment]
Hello again,

I just found out it is only laggy when my dev tools are open, on the ReactDevTools tab.

**Comment by toxicFork** [comment]
Yes react dev tools cannot handle update per frame sadly, they send all
info through the browser in batches and this kills the perf :( thought they
would fix it by now
