### ISSUE TITLE
How to animate child components?

### ISSUE THREAD

**Issue by xseignard** [toxicFork/react-three-renderer#26]
Hello,

Let's say we create some React components that will be included in the React3 scene.

Is the only way to animate them is from the `_onAnimate` function we have on the `React3`?

For now we are trying to use the `_onAnimate` this way (I only put the relevant parts):

```jsx
_onAnimate() {
  this.setState({
    frameNumber: this.state.frameNumber + 1
  });
}

render() {
  return (
    <React3 onAnimate={this._onAnimate}>
      <scene>
        <perspectiveCamera />
        <MyChildComponent frameNumber={this.state.frameNumber} />
      </scene>
    </React3>
  );
}
```

Like this the `MyChildComponent.componentWillUpdate()` will be triggered everytime `_onAnimate` is called. Then we can handle the animation of `MyChildComponent` internally.

Is it a good pattern, or your lib provides something that can achieve the same goal? Or maybe something smarter?

Best regards, and thanks for the `alpha` props!

**Comment by toxicFork** [comment]
Yes that sounds good, another I can think of is to have a store for frame
number and act as if it's an external factor, e.g. a global frame
dispatcher and individual components can listen to a frame event or
something from that, and then set their states if necessary. The main
component could just contact it to dispatch the events. But for simple
situations passing props should be good enough :)

**Comment by xseignard** [comment]
Hello, great to hear we are on the right track! 

When you talk about store and dispatcher, you mean something like redux and thunk? That what we plan to to, but i tried to no introduce noise in the exemple.

Regards, and thanks (again) for your disponibility!

Regards

**Comment by toxicFork** [comment]
Have fun :D
