### ISSUE TITLE
Getting error from React, can't return null, undefined, object...

### ISSUE THREAD

**Issue by ncammarata** [toxicFork/react-three-renderer#3]
Using the Simple example. When I debug it and check out where it throws, I can see that it created the node alright, but the element.type == 1 and React checks to see if it's string or function.

**Comment by toxicFork** [comment]
Hi, thanks for submitting the issue, which browser and os are you seeing this?

**Comment by toxicFork** [comment]
@ncammarata are you still seeing this issue?

**Comment by ncammarata** [comment]
it was for a demo I was building with React a few days ago, but I don't have the demo code any more(was for a talk)

**Comment by toxicFork** [comment]
@ncammarata I'm wondering, was the code you based off of from the wiki or from the examples?
