### ISSUE TITLE
Getting "Warning: Failed propType..." for position and rotation

### ISSUE THREAD

**Issue by mariusk** [toxicFork/react-three-renderer#4]
I've implemented the basic example of the rotation cube from the frontpage, and on the first call to render I get these errors as warnings in the developer console:

```
Warning: Failed propType: Invalid prop `position` of type `<<anonymous>>`
supplied to `perspectiveCamera`, expected instance of `Vector3`.
Check the render method of `ThreeDView`.

Warning: Failed propType: Invalid prop `rotation` of type `<<anonymous>>`
supplied to `mesh`, expected instance of `Euler`.
Check the render method of `ThreeDView`.
```
I've verified (using `this.cameraPosition instanceof THREE.Vector3` and similar for cubeRotation) that they are of the correct types. Any ideas on why it happens and/or workarounds?

Except for the errors on the first call to render, everything seems to work just fine (green cube spinning like mad on a black background).

**Comment by toxicFork** [comment]
I have some thoughts already, I will publish a fix for it this weekend :)
can you paste a gist if possible? Just need to confirm the case.

**Comment by mariusk** [comment]
Sure, here https://gist.github.com/mariusk/b2a1295b95a353e8d5e7. Thanks.

**Comment by toxicFork** [comment]
I think it may be caused by using the 'three' npm module rather than 'three.js'

[1] https://www.npmjs.com/package/three - by bhouston
[2] https://www.npmjs.com/package/three.js - by mrdoob ( original creator of three.js -https://github.com/mrdoob/three.js )

Can you please install three.js and try again?

**Comment by mariusk** [comment]
Tested with `three.js` instead; same error.

**Comment by toxicFork** [comment]
Ah, alright, thanks for confirming! Will submit a fix later today :)

**Comment by toxicFork** [comment]
Hi @mariusk , 

I have just updated the package.

Could you please give it a try with `react-three-renderer@0.0.12-alpha` ? I just tried your gist with this version and I do not seem to be getting warnings, please let me know if it's fixed :)

Technical notes: I was patching THREE.Vector3 and so on with my own replacements - only in non production environments - in order to give proper react warnings instead of <<anonymous>> but that had some side effects, including this one.

I am now using [my own copy of PropTypes.instanceOf](https://github.com/toxicFork/react-three-renderer/blob/master/src/utils/propTypeInstanceOf.js). I will create an issue on THREE.js that when fixed will make this unnecessary.

**Comment by mariusk** [comment]
When trying to install the latest version using `npm`, I get the following error:

```
$ npm install react-three-renderer@latest
eplas@1.0.0 /Users/marius/p/eplas
└── react-three-renderer@0.0.12-alpha  invalid
```
The same happens if I replace `latest` with `0.0.12-alpha` as well.

**Comment by toxicFork** [comment]
I think that's an issue with npm e.g. some packages may be conflicting, it seems to work on my machine:
```bash
Firtina@surfie MINGW64 ~/work/testnpm
$ npm install react-three-renderer@latest
testnpm@1.0.0 C:\Users\Firtina\work\testnpm
└── react-three-renderer@0.0.12-alpha

npm WARN EPACKAGEJSON testnpm@1.0.0 No description
npm WARN EPACKAGEJSON testnpm@1.0.0 No repository field.
```

**Comment by toxicFork** [comment]
Sorry misclicked... according to http://stackoverflow.com/questions/25696584/npm-list-giving-npm-err-invalid-output a `npm update` may work or, perhaps you can manually remove the node modules directory and reinstall, I am guessing there may be some dependency conflicts as well (maybe different versions of react / three.js ? )

**Comment by toxicFork** [comment]
Also I'm guessing it could depend on the NPM version, I am using npm --v `3.3.8`, which npm version are you on? I'll try on your version as well :)

**Comment by mariusk** [comment]
I'm on 3.3.12. I'll give reinstalling a try later today.

**Comment by toxicFork** [comment]
Alright, I will upgrade my npm version to 3.3.12 as well to confirm. Can you paste your package.json at the current state if possible? At least the dependencies sections.

**Comment by mariusk** [comment]
Wiped node_modules and reinstalled. At least 0.0.12 got installed now. But I still get the same propType errors.

**Comment by toxicFork** [comment]
Could you please upload a zip of your project folder, or at least a package.json with dependencies and dev dependencies, the relevant js files, and configs e.g. webpack config? You can email me at firtina14@gmail.com

**Comment by mariusk** [comment]
Sorry, can't do that. I haven't created a minimal sample yet (it's part of a bigger project). If you're not having any of the issues I'm seeing then this shouldn't be a problem for most people I guess. In my project I'll be wrapping three.js directly for now. The ticket is here now, so if anybody else is having issues they should be able to find it (and continue the hunt for the actual issue).

**Comment by mariusk** [comment]
Oh, and thanks for helping out!

**Comment by toxicFork** [comment]
Alright, I think it's because somehow there may be multiple copies of
three.js around and the one react three renderer can see is different than
the one "outside" (maybe version clashes), but thanks for reporting, I'll
keep an eye on it!

**Comment by mariusk** [comment]
There's definitively an issue of multiple versions of libraries. I noticed the first time I installed this package that my bundled js almost doubled. I suspect I had a newer version of react than your library pulled in, but I never took the time to figure out the exact cause. I really need to take the time to learn how npm package dependencies really work...

**Comment by PolGuixe** [comment]
I am experiencing this issue as well mainly becuase I wrapped `three.js` from npm, into another package that adds more libraries into it. Nothing fancy. https://github.com/Zetoff/zetoff-three

But maybe I have to think the way I add those libraries.

**Comment by toxicFork** [comment]
It should not be a problem as long as same exact versions of three are used for both libraries, which versions do you see on your directories?

**Comment by PolGuixe** [comment]
Both libraries are using v0.77.1. Hence, it is a bit weird.

**Comment by toxicFork** [comment]
Hmm hmm hmm... I will try to repro on my end

**Comment by PolGuixe** [comment]
worth havign a look here ? https://github.com/mrdoob/three.js/issues/6362

**Comment by Carnewal** [comment]
Came across this today and didn't find a solution. 

Wouldn't it be a possiblity to expose Three.js from react-three-renderer ?

**Comment by toxicFork** [comment]
Are you also using a different threejs version as well? It wouldn't be nice
for a npm package to expose a dependency...

**Comment by Carnewal** [comment]
I'm using staging/2.3 (for the invalid PropTypes issue) with three 0.79.0

**Comment by bebbi** [comment]
I have a (npm) set up
app
|_component1 that depends on THREE
|_component2 that depends on react-three-renderer
|_THREE 0.79 required by react-three-renderer

Component1  depends on THREE@^0.80 so I tried with wrapping it in a package that also packs THREE r80)

Passing objects from a hidden THREE instance into react-three-renderer works (r80 mainly changes three to use ES2015 modules), but it will of course make the instanceOf propTypes fail.

It might "kind of work" to serialize and load all the outputs from component1 into the top THREE instance.

Related:
r80 also adds some methods to identify objects - e.g. for geometry.
`Geometry.prototype.isGeometry = true`

in addition to (old, in constructor):
`this.type = 'Geometry';`

Possibly those can help avoid some of the warnings altogether.
(Btw, are you planning to move to r80 anytime soon? The module stuff is cool..)
