### ISSUE TITLE
Is there a danger in declaring a <geometry> resource outside of a <resource> tag?

### ISSUE THREAD

**Issue by DelvarWorld** [toxicFork/react-three-renderer#45]
I'm trying to track down a performance issue. I'm making about 40 individual `<textGeometry />` objects, but in a standalone file not wrapped in a `<resources>` tag. I put them in my app like:

```js
            <resources>
                { otherResources }
                { lettersArray }
            </resources>
```

Simply adding the array of `<textGeometry />`s (`lettersArray` in this case ) drops my framerate from 60 to 10. I tried to reproduce this in a standalone example but there was no FPS drop when including the same amount of geometry objects directly in a resource tag. I'm not sure what else to look at yet. Is it ok to declare a `<textGeometry />` etc component outside of a render function and outside of a `<resources>` tag?

**Comment by toxicFork** [comment]
To be able to help resolve this I'll need to see code snippets for both versions - the one with fps drop and one without - , live examples would be best :)

**Comment by DelvarWorld** [comment]
The culprit was putting the entire array in the same component as `<react3>`. Moving it into its own component fixed it :)
