### ISSUE TITLE
[ArrowHelper] bug updating prop 'origin'

### ISSUE THREAD

**Issue by Colmea** [toxicFork/react-three-renderer#59]
Just a reminder for the bug in the Arrow Helper.

'origin' prop throws a warning on each frame: "_warning.js:44 Warning: updating prop origin ( [object Object] ) for ArrowHelperDescripto_r"

I would like to help you but cannot undertand where I should fix this bug :D

**Comment by toxicFork** [comment]
Thanks for the report, I remember it from the chat :) This will make it easier to track, I fill fix this as soon as possible!
