### ISSUE TITLE
Can't change the number of vertices in geometry.

### ISSUE THREAD

**Issue by Anton-2** [toxicFork/react-three-renderer#64]
The number of vertices given to a geometry seems to be cached on creation.
When rendering a new vertex list, the new values are read, but adding or removing vertices has no effect.

demo : https://gist.github.com/Anton-2/848f6ec3642ae616e3eaeae5699db3c1

**Comment by toxicFork** [comment]
Thank you for the report :) I will take a look asap.

**Comment by Anton-2** [comment]
Thanks, but it looks like react-three-renderer is not concerned !

I should have searched a little better : it's a design decision, in three.js : https://github.com/mrdoob/three.js/wiki/Updates#geometries

It seems that the only solution is to over-allocate the vertex list, and draw only the elements I need.
Based on http://stackoverflow.com/questions/31399856/drawing-a-line-with-three-js-dynamically, I'll try to do this with ```setDrawRange```, and see if I can add this property to geometry in react-three-renderer.

**Comment by toxicFork** [comment]
Oh I see... cool :)
