### ISSUE TITLE
Lighting missing position and rotation

### ISSUE THREAD

**Issue by axiomaticdesign** [toxicFork/react-three-renderer#65]
I've noticed the `directionalLight` component doesn't utilize the `position` prop as expected. It doesn't look like `position` or `rotation` gets used in the descriptor base or the actual component. 

Should the position and rotation be set like `this.refs.myLight.position.set(0, 1, 0)` or should I just build the capability into my fork?

If the first way is ideal, a quick wiki update would solve this.

**Comment by toxicFork** [comment]
It should use the position and rotation props, perhaps there's a bug, I
will take a look asap (probably this weekend)! So does updating the
position prop do nothing? Also does the ref position update work as a
workaround?

**Comment by toxicFork** [comment]
Threejs ignores the position of directional lights because they are assumed to be at an infinite distance and have parallel rays, but the rotation should affect how the scene is lit. If that does not happen then there is a bug somewhere. I could update the documentation for directional light position to reflect that :)

**Comment by axiomaticdesign** [comment]
The update by ref does work (in `componentDidMount` at least). I can't find anywhere in the code where position gets set, so I've just made sure the position is being explicitly set in `directionalLight` which does seem to have an effect on the map.

I had the idea to set it in `componentDidMount` from #57 because I used that same method to include an MTL/OBJ.

**Comment by toxicFork** [comment]
OK It looks like the directional light object in THREE uses a `target` object instead of `rotation` for some very strange reason. I will update the code to fix that. Good find!

**Comment by toxicFork** [comment]
Update on this, I am implementing catching `rotation`, `quaternion` and `lookAt`property updates and making that update the target as well, it should work seamlessly. Please comment if you would like to use a `targetPosition` property instead, which would be "less magic".

**Comment by toxicFork** [comment]
More detail on threejs behavior: by default directionalLight points at origin and looks downwards. Current workaround: move the directional light position ( The `position` prop should still work for this ), and it will always point to origin. For example if you want it to look forward `(0,0,1)`, set the position to be `(0, 0, -1)`, for `(1,2,3)` set position to be `(-1, -2, -3)`, and so on.
