### ISSUE TITLE
Add textureLoader.crossOrigin

### ISSUE THREAD

**Issue by DelvarWorld** [toxicFork/react-three-renderer#7]
Somewhere around here:

https://github.com/toxicFork/react-three-renderer/blob/136ff25e6992f200aafa41324b070a7a04768b67/src/descriptors/Material/TextureDescriptor.js#L12

The textureLoader has a crossOrigin prop:

http://threejs.org/docs/#Reference/Loaders/TextureLoader.crossOrigin

It's not on the texture itself. Setting it to empty string `""` allows you to load images from a different domain. See http://stackoverflow.com/questions/24087757/three-js-and-loading-a-cross-domain-image

**Comment by toxicFork** [comment]
I will add this, thanks :)
