### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by buildbreakdo** [toxicFork/react-three-renderer#70]
Could the license for this repo please be added? Did not see a license file or anything stated at the top of files.  Would love to use and contribute, looking for some clarity.

**Comment by toxicFork** [comment]
I'm unsure regarding the license, it has modified copies of a bit of react internals (BSD), but I personally prefer MIT license. Unfortunately I do not know enough about these things to verify whether MIT would be suitable. Any thoughts?

**Comment by toxicFork** [comment]
I'll just go for MIT :)

**Comment by buildbreakdo** [comment]
Haha -- cool! May was a crazy month (quit Microsoft!) and started a move to India, this fell off the radar, whoops! Love the work you're doing!

**Comment by toxicFork** [comment]
Oh yeah that sounds like a very crazy month indeed!! Mine's been a bit less
crazy but still stupidly busy :)
