### ISSUE TITLE
warning on loading textures, using minFilter, magFilter

### ISSUE THREAD

**Issue by jardakotesovec** [toxicFork/react-three-renderer#75]
I am getting several warnings using scene like this. Texture is png image.
```
[.CommandBufferContext]RENDER WARNING: there is no texture bound to the unit 0
three.js:27674 THREE.WebGLRenderer: image is not power of two (432x305). Resized to 512x256 <img src=​"/​img/​views/​main/​UP-735/​1/​1?PVI-816">​
three.js:28591 THREE.WebGLRenderer: WEBGL_compressed_texture_pvrtc extension not supported.
three.js:28591 THREE.WebGLRenderer: WEBGL_compressed_texture_etc1 extension not supported.
three.js:27400 WebGL: INVALID_ENUM: texParameter: invalid parameter
three.js:27401 WebGL: INVALID_ENUM: texParameter: invalid parameter
```
```
            <React3
                mainCamera='camera'
                width={canvasWidth}
                height={canvasHeight}
            >
                <scene>
                    <perspectiveCamera
                        name="camera"
                        fov={35}
                        aspect={canvasWidth / canvasHeight}
                        near={0.1}
                        far={5000}

                        position={new THREE.Vector3(0, 0, 750)}
                    />
                    <object3D>
                        <mesh>
                            <meshBasicMaterial color={0xff0000} side={THREE.FrontSide}>
                                    <texture
                                        url={imageUrl}
                                    />
                            </meshBasicMaterial>
                            <planeBufferGeometry width={page.width} height={page.height} />
                        </mesh>
                    </object3D>
                </scene>
            </React3>
```

Wondering why, because when I used Three.js directly, it did not get any warnings. 
```
new t.TextureLoader().load( imageUrl, (texture) => {
  texture.minFilter = texture.magFilter = t.LinearFilter;
  var material = new t.MeshBasicMaterial( { color: 0xffffff, map: texture, side:  t.FrontSide } );
  mesh.material = material;
```

Lets elaborate on warnings bit more:
```
three.js:27674 THREE.WebGLRenderer: image is not power of two (432x305). Resized to 512x256 <img src=​"/​img/​views/​main/​UP-735/​1/​1?PVI-816">​
```
Was supposed to be solved by `texture.minFilter = texture.magFilter = t.LinearFilter;`, but did not manage to achieve that in react-three-rendered. I tried using refs in componentDidUpdate as well as using onLoad callback.

```
[.CommandBufferContext]RENDER WARNING: there is no texture bound to the unit 0
```
This one is maybe related to https://github.com/mrdoob/three.js/issues/8666, but I am not getting this message with same THREE.js scene.

And don't know why I am getting 
```
three.js:28591 THREE.WebGLRenderer: WEBGL_compressed_texture_pvrtc extension not supported.
three.js:28591 THREE.WebGLRenderer: WEBGL_compressed_texture_etc1 extension not supported.
three.js:27400 WebGL: INVALID_ENUM: texParameter: invalid parameter
three.js:27401 WebGL: INVALID_ENUM: texParameter: invalid parameter
```

Btw really love the abstraction you have achieved, just trying to decide if its too young to be used for serious project at the point..

**Comment by jardakotesovec** [comment]
These warnings were coming from chrome, in firefox its same except the 
```
[.CommandBufferContext]RENDER WARNING: there is no texture bound to the unit 0
```
which is not present there. So lets assume that this one is chrome issue.

**Comment by toxicFork** [comment]
> just trying to decide if its too young to be used for serious project at the point..

Yes it is too young at the moment :)

I will take a look at the props for texture and see if I can add anything to resolve this issue.

**Comment by jardakotesovec** [comment]
>  Yes it is too young at the moment :)

Right. Thing is that organizing scene into react components got addictive very quickly and its hard to stop :-). So I guess I will have to accept that risk :-).

So far I solved texture loading in `componentDidMount`, which seems to work fine for me (until it will be possible to express it declaratively). Just would love to hear your feedback if you see some issues with adjusting THREE objects like that or you find it reasonable. 

```
    componentDidMount: function() {
        new THREE.TextureLoader().load( '/url', (texture) => {
            if(this.isMounted()) {
                texture.minFilter = texture.magFilter = THREE.LinearFilter;
                var material = new THREE.MeshBasicMaterial( { color: 0xffffff, map: texture, side: THREE.FrontSide } );
                this.refs.frontSide.material = material;
            }
        } );
    },
```
And in render I have
```
                <mesh ref='frontSide' name={`page:${frontPageId}`} >
                    <meshBasicMaterial color={0xff0000} side={THREE.FrontSide} />
                    <planeBufferGeometry width={width} height={height} />
                </mesh>
``` 

My assumption is that if I don't change that `meshBasicMaterial` in render during component life cycle (so it does not fight with the changes I have made in `componentDidMount`) it should be fine.

**Comment by toxicFork** [comment]
Yes that should work :) until I fix the props for texture at least!

**Comment by toxicFork** [comment]
And I'm happy to hear that you like the project :D

**Comment by toxicFork** [comment]
See 6bb66b8
