### ISSUE TITLE
linewidth not camel cased

### ISSUE THREAD

**Issue by DelvarWorld** [toxicFork/react-three-renderer#8]
see https://github.com/toxicFork/react-three-renderer/blob/414d6ea91e4773be18646c6a71512bbb2b3b2cc6/docs/src/internalComponents/lineBasicMaterial.js#L22

**Comment by toxicFork** [comment]
Same here: http://threejs.org/docs/#Reference/Materials/LineBasicMaterial.linewidth :(

**Comment by toxicFork** [comment]
But I could do th better thing here I guess ;)

**Comment by toxicFork** [comment]
Will not change unless it's changed within three
