### ISSUE TITLE
Does not work with React v15.2.0

### ISSUE THREAD

**Issue by dlindenkreuz** [toxicFork/react-three-renderer#85]
```
ERROR in ./frontend/~/react-three-renderer/lib/React3Renderer.js
Module not found: Error: Cannot resolve module 'react/lib/getNativeComponentFromComposite' in /Users/daniel/Documents/Code/x/frontend/node_modules/react-three-renderer/lib
 @ ./frontend/~/react-three-renderer/lib/React3Renderer.js 65:39-91
```

using react-three-renderer v2.1.3 and react v15.2.0

**Comment by toxicFork** [comment]
Thanks for the report, I will update the lib ASAP

**Comment by toxicFork** [comment]
Still working on this, getting some progress, still need to fix the annoying unkown prop warnings...

**Comment by bitttttten** [comment]
Hey,

Would you mind providing versions of `react-three-renderer` and `react` that are compatible? I installed `react-three-renderer` today and I was given this same error.

Thanks in advance.

**Comment by toxicFork** [comment]
Latest react three renderer should work with react@~15.1.0

**Comment by bitttttten** [comment]
Great, thanks. And thanks for the quick reply!

**Comment by toxicFork** [comment]
2.2.0 should fix this :)
