### ISSUE TITLE
threeObject.userData._triggerRemount is not a function.

### ISSUE THREAD

**Issue by toxicFork** [toxicFork/react-three-renderer#86]
See https://stackoverflow.com/questions/38212807/react-three-renderer-polyhedrongeometry-error

**Comment by toxicFork** [comment]
Technical details: when you modify some props on certain types such as Polyhedron Geometry, it will trigger a remount of the component to recreate the geometry object and let threejs now that there's a new geometry. In this case the library developer (me) forgot to handle a case that happens during initial construction of the object.

**Comment by sehcheese** [comment]
Great, thanks! Is there a target publish time for 2.2.0?

**Comment by toxicFork** [comment]
Hopefully this weekend, still need to find out how to deal with all of the extra warnings react 15.2 now gives, in worst case I can publish a 2.1.x with this fix instead :)

**Comment by toxicFork** [comment]
Should be fixed in https://github.com/toxicFork/react-three-renderer/releases/new?tag=v2.1.4 :)
