### ISSUE TITLE
Does not work with ThreeJS 0.78.0

### ISSUE THREAD

**Issue by robatosan** [toxicFork/react-three-renderer#87]
I'm getting an "unmet peer dependency" error with the current three.js version
`npm WARN react-three-renderer@2.1.3 requires a peer of three@>=0.74.0 < 0.78.0 but none was installed`

**Comment by toxicFork** [comment]
Hi thanks for the report, it should still work even though it gives the
unsupported warning, in the next update we will bump the supported version
after all tests are confirmed to pass

**Comment by toxicFork** [comment]
2.2.0 should fix this :)
