### ISSUE TITLE
Uncaught TypeError: _this3._renderer.setViewport is not a function

### ISSUE THREAD

**Issue by bitttttten** [toxicFork/react-three-renderer#89]
Hey,

I'm running into the above error on each step. I was using my own components, although I stripped them back to use your example code and I am still getting the same error. Am I missing something stupidly obvious, or is this a bug?

Console output:

> Uncaught TypeError: _this3._renderer.setViewport is not a function_render @ React3Instance.js:1024

..and console log output from load of page:

> THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.jsTHREE.CanvasRenderer @ three.js:33665_createRenderer @ React3Instance.js:179updateCanvas @ React3Instance.js:664setParent @ React3Descriptor.js:207_mountImageIntoNode @ React3Renderer.js:595React3Renderer.mountComponentIntoNode @ React3Renderer.js:429perform @ Transaction.js:136React3Renderer.batchedMountComponentIntoNode @ React3Renderer.js:421batchedUpdates @ ReactDefaultBatchingStrategy.js:61batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ React3Renderer.js:991_renderSubtreeIntoContainer @ React3Renderer.js:702render @ React3Renderer.js:621_render @ React3.js:88componentDidMount @ React3.js:66invokeComponentDidMountWithTimer @ ReactCompositeComponent.js:63notifyAll @ CallbackQueue.js:66close @ ReactReconcileTransaction.js:79closeAll @ Transaction.js:202perform @ Transaction.js:149batchedMountComponentIntoNode @ ReactMount.js:123perform @ Transaction.js:136batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ ReactMount.js:286_renderSubtreeIntoContainer @ ReactMount.js:365render @ ReactMount.js:386(anonymous function) @ index.js:16(anonymous function) @ build.js:8201(anonymous function) @ build.js:8202__webpack_require__ @ bootstrap 767f813…:555fn @ bootstrap 767f813…:86(anonymous function) @ bootstrap 767f813…:578__webpack_require__ @ bootstrap 767f813…:555(anonymous function) @ bootstrap 767f813…:578(anonymous function) @ bootstrap 767f813…:578

> Uncaught TypeError: _this3._renderer.setViewport is not a function_render @ React3Instance.js:1024

The versions I am using:

```
"react": "15.1.0",
"react-dom": "^15.2.1",
"react-three-renderer": "^2.1.4",
"three": "0.77.0",
```

And the 2 files:

```
// -----------------
// components/app.js
import React, { Component } from 'react'
import React3 from 'react-three-renderer'
import THREE from 'three'

export default class App extends Component {

    constructor(props, context) {
        super(props, context)

        this.onChangeComplete = this.handleChangeComplete.bind(this)
        this.onChange = this.handleChange.bind(this)
        this.onWindowResize = this.handleWindowResize.bind(this)

        this.state = {
            colour: '#ff00ff',
            width: 500,
            height: 400,
            cameraPosition: new THREE.Vector3(0, -300, 500),
            lightPosition: new THREE.Vector3(0, 500, 2000),
            lightTarget: new THREE.Vector3(0, 0, 0)
        }
    }

    componentDidMount() {
        window.addEventListener('resize', this.onWindowResize)
    }

    componentWillUnmount() {
        window.removeEventListener('resize', this.onWindowResize)
    }

    handleWindowResize() {
        
    }

    render() {
        return (
            <div>
                <h1>Hello!</h1>

                <React3
                  mainCamera="camera"
                  width={this.state.width}
                  height={this.state.height}
                >
                  <scene>
                    <perspectiveCamera
                      name="camera"
                      fov={75}
                      aspect={this.state.width / this.state.height}
                      near={0.1}
                      far={1000}

                      position={this.state.cameraPosition}
                    />
                    <mesh>
                      <boxGeometry
                        width={1}
                        height={1}
                        depth={1}
                      />
                      <meshBasicMaterial
                        color={0x00ff00}
                      />
                    </mesh>
                  </scene>
                </React3>
            </div>
        )
    }

}

// -----------------
// app.js
import React from 'react'
import ReactDOM from 'react-dom'

import App from './components/App'

ReactDOM.render( <App />, document.getElementById('app') )
```

**Comment by bitttttten** [comment]
This was because there was no webgl instance, and (I guess) it was trying to fall back to the CanvasRenderer.

A duplicate of https://github.com/toxicFork/react-three-renderer/issues/79, then. So I will close this.

**Comment by toxicFork** [comment]
Thanks for the report, hopefully once CanvasRenderer is fixed this should go away too
