### ISSUE TITLE
debugging: forgetting to put resourceId in side <resources>

### ISSUE THREAD

**Issue by DelvarWorld** [toxicFork/react-three-renderer#9]
I just spent a while debugging why my app was crashing,

```
THREE.Object3D.add: object not an instance of THREE.Object3D. T…E.Shape {curves: Array[1], autoClose: false, actions: Array[2], holes: Array[0], userData: Object…}
```

Even though I was copying the examples. It turned out to be that my `<shape resourceId="" />` wasn't in a `<resources>` tag. Is there any way to give a nice error message if this is the case? if not this tickent can be closed

**Comment by toxicFork** [comment]
Thanks for the report, I will try to fix this. Could you please upload a sample repro for it?
