### ISSUE TITLE
Material Shading options

### ISSUE THREAD

**Issue by PolGuixe** [toxicFork/react-three-renderer#91]
Is there a way to change the shading option for the materials? 

It looks like  the MeshPhongMaterial accepts: `shading={THREE.FlatShading}` and `shading={THREE.SmoothShading}`, but it is not in the documentation.

**Comment by toxicFork** [comment]
Thanks for the report, sending code and doc gremlins

**Comment by toxicFork** [comment]
See b2e6f85

**Comment by PolGuixe** [comment]
Nice! ;)
