### ISSUE TITLE
TorusKnotGeometry has radialSegments and tubularSegments functionally reversed

### ISSUE THREAD

**Issue by DodekaHydra** [toxicFork/react-three-renderer#93]
The React3 implementation of TorusKnotGeometry seems to have some properties reversed.

If you check the THREE.js documentation for [TorusKnotGeometry](http://threejs.org/docs/#Reference/Extras.Geometries/TorusKnotGeometry), you will see that tubular segments increase the number of segments along the path of the knot, while radial segments increase the number of segments along any ring/cross-section of the knot.  High radial + low tubular makes the knots out of an approximation of cylinders. High tubular + low radial makes the knots look more like a race track.

In the following image, you'll see React3 with high radial and low tubular:
![chrome_2016-08-02_11-05-19](https://cloud.githubusercontent.com/assets/4563407/17339528/33562fe2-58a1-11e6-8bb1-59d4285b4481.png)

Here's low radial and high tubular:
![chrome_2016-08-02_11-05-52](https://cloud.githubusercontent.com/assets/4563407/17339536/38cd6c7e-58a1-11e6-9c47-3028d681a5e9.png)

I briefly checked the source in an attempt to isolate the bug but didn't see what could be causing this.

**Comment by toxicFork** [comment]
Thanks for reporting, it will be fixed ASAP!

**Comment by DodekaHydra** [comment]
No problem. I want to say, I really like this library so far, even if it doesn't cover 100% of THREE.js's functionality.

Do you have contributor guidelines for pull requests of new features? I especially want to make physically-based materials work! http://threejs.org/examples/?q=material#webgl_materials_variations_physical

**Comment by toxicFork** [comment]
Thanks :D 

Regarding contributor guidelines, one will be created soon(tm) :)
