### ISSUE TITLE
Does not work with React v15.3.0

### ISSUE THREAD

**Issue by dlindenkreuz** [toxicFork/react-three-renderer#94]
> Warning: You are manually calling a React.PropTypes validation function for the `position` prop on `perspectiveCamera`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details. [1]

> Uncaught TypeError: Cannot read property 'emit' of undefined [2]

using react-three-renderer v2.2.0 and React v15.3.0

As soon as an object is unmounted, my console gets spammed with errors and warnings :smile:

I get [1] for lots of components: perspectiveCamera, directionalLight, ambientLight, object3D, sprite etc.

[2] author's note: happens when calling `this.threeElementDescriptor.unmount(this._threeObject);`

**Comment by dlindenkreuz** [comment]
You should consider adding a note to the README that only React v15.2.x (eventually other versions) are supported with the most current version of react-three-renderer. Not everyone reads npm `peerDependencies` warnings carefully enough.

**Comment by toxicFork** [comment]
Good idea! :) thanks for the report! Looks like every minor react version
breaks us :P

**Comment by dlindenkreuz** [comment]
yeah, it's pretty much time that React opens their gates for 3rd party renderer implementations. piggybacking on private APIs sucks in the long term. thank you, @toxicFork, for relentlessly keeping on top of those changes!
