### ISSUE TITLE
SpriteMaterial : Support for texture map is missing

### ISSUE THREAD

**Issue by chanakyabhardwajj** [toxicFork/react-three-renderer#95]
I noticed that the [SpriteMaterialDescriptor](https://github.com/toxicFork/react-three-renderer/blob/master/src/lib/descriptors/Material/SpriteMaterialDescriptor.js) has no support for the [texture map](http://threejs.org/docs/api/materials/SpriteMaterial.html) property.

Any specific reason behind this? Or is it a bug?

**Comment by DodekaHydra** [comment]
If you set the ref property of your object like this:
    <mesh
        ref="mesh"
    >

You can then modify that mesh later, for example, inside your `componentDidMount()` method:
    componentDidMount() {
        const map = do_some_stuff()
        this.refs.mesh.material.map = map
    }

**Comment by toxicFork** [comment]
For materials you should be able to set its map by declaring the texture within:

```jsx
<...material>
    <texture .../>
</...material>
```

If that doesn't work that's a bug :)

[ ] I'll update the documentation for all materials to clarify this

**Comment by chanakyabhardwajj** [comment]
@DodekaHydra, @toxicFork: Thanks for the answer 👍
