### ISSUE TITLE
Can I load image texture on runtime or play video?

### ISSUE THREAD

**Issue by pencil001** [toxicFork/react-three-renderer#96]
With native three.js, I can change the image texture with the following code:
```
const texture = new THREE.TextureLoader().load(filePath);
this.mesh.material.map = texture
```

And I also can play video:
```
const video = document.getElementById('videoplayer');
const texture = new THREE.Texture(video);
this.mesh.material.map = texture
```

How can I do the same things in react3? Thank you!

**Comment by toxicFork** [comment]
For materials you should be able to set its map by declaring the texture within:

```jsx
<...material>
    <texture .../>
</...material>
```

For `new TextureLoader().load(url)` see [the url prop for texture](https://github.com/toxicFork/react-three-renderer/wiki/texture#url).

Regarding video, I will need to implement that as a new prop.

**Comment by pencil001** [comment]
Thanks!
