### ISSUE TITLE
Functions continue to run after component un-mounts?

### ISSUE THREAD

**Issue by samcorcos** [toxicFork/react-three-renderer#99]
I have a React3 component that lives in a modal. When the modal opens the first time, everything works perfectly. My 3D model renders and rotates as expected. 

Problems arise when I try closing it. First I get the following error as soon as I close the modal:

```
Uncaught TypeError: Cannot set property 'heightSegments' of null
```

The only place this is being called is within a ref `<planeGeometry ref={this.plan} ...`, where `plan` is a function. 

When the component re-mounts, React3 does not re-render, but there are also no errors. Then when the component is re-un-mounted (close the modal a second time), I get the following error, which runs ~50 times a second:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.
```

Then when I re-re-mount (open the modal a third time), the 3D model does render but it's really choppy, which leads me think that there is a process in the background that was never stopped. 

Any thoughts on what I could be doing wrong? I'm happy to try to provide a minimum reproducible bug if that becomes necessary.

**Comment by toxicFork** [comment]
Hi, yes a minimum repro would help a great deal, perhaps React3 may not be cleaning up perfectly

**Comment by samcorcos** [comment]
Could not reproduce in small scale. Will reopen if I can.
